markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Limags"

author: "Limags"
atom-baseurl: "http://limags.com"
#disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: GitHub
    class: fa fa-github
    href: https://github.com/Limags	
  - title: Wordpress
    class: fa fa-wordpress
    href: http://programmemo.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
  - title: About
    class: fa fa-user
    href: /about.html
